overview of ispor branch
hta-pharma/maicplus pull request #65
Opened 2023-10-30 13:09 UTC by gravesti

2023-11-03 15:24 UTC, MikeJSeo requested changes
I just briefly reviewed kmplot function parameters.

2023-11-24 08:49 UTC, gravesti commented on inst/examples/kmplot_unanchored_ex.R
> +        endpoint_name = "Overall Survival",
Implement the above reordering.

`pseudo_ipd` -> `pseudo_agd`
maybe `weighted_ipd` instead of `ipd_weights`?

2023-11-24 08:54 UTC, gravesti commented on inst/examples/kmplot_unanchored_ex.R
> +        endpoint_name = "Overall Survival",
- [ ] add the checks for time scale and time grid

2024-01-19 09:42 UTC, gravesti commented on inst/examples/kmplot_unanchored_ex.R
> +        endpoint_name = "Overall Survival",
- [ ] make sure we use logHR from coxph

2024-01-22 09:14 UTC, gravesti commented
@MikeJSeo @hoppanda This looks ready to merge. The only thing left are some style issues but let's look at those later. Can you please give approval to merge?

2024-01-23 08:58 UTC, gravesti commented
@MikeJSeo @hoppanda All the tests are passing now. Can one of you approve this pull request?

2024-01-24 11:41 UTC, merged